# Generated by Django 4.2.13 on 2024-10-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedoc', models.CharField(choices=[('D', 'DNI'), ('CE', 'CARNET EXTRANJERIA')], max_length=5)),
                ('pdoc', models.CharField(max_length=20)),
                ('last_name0', models.CharField(max_length=150)),
                ('last_name1', models.CharField(max_length=150)),
                ('names', models.CharField(max_length=150)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('pmail', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=9, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('user_create', models.CharField(blank=True, max_length=50, null=True)),
                ('user_update', models.CharField(blank=True, max_length=50, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'unique_together': {('pdoc',)},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario de sistema',
                'verbose_name_plural': 'Usuarios del sistema',
            },
        ),
    ]
