# Generated by Django 4.2.13 on 2025-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('DP', 'DEPARTAMENTO'), ('PR', 'PROVINCIA'), ('DS', 'DISTRITO')], max_length=2, null=True),
        ),
    ]
