# Generated by Django 4.2.13 on 2025-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_user_code_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('DP', 'DEPARTAMENTO'), ('PR', 'PROVINCIA'), ('MR', 'MICRORED'), ('DS', 'DISTRITO')], max_length=2, null=True),
        ),
    ]
