# Generated by Django 4.2.13 on 2024-11-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_establecimiento_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
