# Generated by Django 4.2.13 on 2024-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
