# Generated by Django 4.2.13 on 2025-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profesion'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='microred',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='microred',
        #     name='codigo',
        #     field=models.CharField(max_length=3),
        # ),
    ]
