# Generated by Django 4.2.13 on 2025-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_microred_id_alter_microred_codigo'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='microred',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='microred',
        #     name='codigo',
        #     field=models.CharField(max_length=3, primary_key=True, serialize=False),
        # ),
    ]
