# Generated by Django 4.2.13 on 2025-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_microred_id_alter_microred_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='distrito',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='microred',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='mred',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nred',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nsector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
