# Generated by Django 4.2.13 on 2025-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_microred_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='mred',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='microred',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
        # migrations.AddField(
        #     model_name='microred',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
