# Generated by Django 4.2.13 on 2025-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_microred_id_alter_distrito_mred_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='microred',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
