# Generated by Django 4.2.13 on 2025-01-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_microred_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microred',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
