# Generated by Django 4.2.13 on 2025-01-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_microred_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='microred',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='distrito',
        #     name='mred',
        #     field=models.CharField(blank=True, max_length=6, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='microred',
        #     name='codigo',
        #     field=models.CharField(max_length=3, primary_key=True, serialize=False),
        # ),
    ]
