# Generated by Django 4.2.13 on 2025-01-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_distrito_mred_remove_microred_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='dist',
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
    ]
