# Generated by Django 4.2.13 on 2025-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_establecimiento_dist_delete_distrito'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='microred',
        #     name='codigo',
        #     field=models.CharField(blank=True, max_length=3, null=True),
        # ),
    ]
