# Generated by Django 4.2.13 on 2025-01-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_microred_establecimiento_nmred_distrito_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='microred',
        #     old_name='id',
        #     new_name='mid',
        # ),
        migrations.AddField(
            model_name='distrito',
            name='nmred',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
