# Generated by Django 4.2.13 on 2025-01-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_id_microred_mid_distrito_nmred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicroRed',
        ),
    ]
