# Generated by Django 4.2.13 on 2025-01-18 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_microred'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=60)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departamento')),
                ('prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.provincia')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.red')),
            ],
        ),
    ]
